title: JTF CODING
description: "August 2023 to June 2024"
owner_name: Theo Huntalas
github_username: TheoH32
github_repo: "jtf-blog"
baseurl: "/jtf-blog"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/TheoH32"}
    - { platform: github, user_url: "https://github.com/F1nnC"}
    - { platform: github, user_url: "https://github.com/jyusin"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
